// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3n0siSMHVSOxTVo3JQEjEZraz56Y6bUM',
    appId: '1:621172961214:web:11261828c933002dfe53ef',
    messagingSenderId: '621172961214',
    projectId: 'pubauthwoc',
    authDomain: 'pubauthwoc.firebaseapp.com',
    storageBucket: 'pubauthwoc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7DjRjniKs6Ek1FH8ml-2kQSzaDba8z50',
    appId: '1:621172961214:android:1a66240682ee00f3fe53ef',
    messagingSenderId: '621172961214',
    projectId: 'pubauthwoc',
    storageBucket: 'pubauthwoc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEnTAOGk2dthu4x_JEnVWwJJC-5DZAo68',
    appId: '1:621172961214:ios:dbef9b9b1028f63bfe53ef',
    messagingSenderId: '621172961214',
    projectId: 'pubauthwoc',
    storageBucket: 'pubauthwoc.appspot.com',
    iosClientId: '621172961214-8kpvbf8krle0gtbhuu73ne6la5sqpipk.apps.googleusercontent.com',
    iosBundleId: 'com.example.pubAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEnTAOGk2dthu4x_JEnVWwJJC-5DZAo68',
    appId: '1:621172961214:ios:dbef9b9b1028f63bfe53ef',
    messagingSenderId: '621172961214',
    projectId: 'pubauthwoc',
    storageBucket: 'pubauthwoc.appspot.com',
    iosClientId: '621172961214-8kpvbf8krle0gtbhuu73ne6la5sqpipk.apps.googleusercontent.com',
    iosBundleId: 'com.example.pubAuth',
  );
}
